# Laboratory Work #4
## Group: IT2-2404SE
## Full Name: Daniil Kalts

In [2]:
import numpy as np

### 1. Create the following NumPy arrays:

#### a) A 1-D array called _zeros_ having 10 elements and all the elements are set to zero.

#### b) A 1-D array called _vowels_ having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.

#### c) A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int.

####  d) Use nested Python lists to create a 2-D array called _myarray1_ having 3 rows and 3 columns and store the following data:
         2.7, -2, -19
         0, 3.4, 99.9
         10.6, 0, 13
#### e) A 2-D array called _myarray2_ using _arange()_ having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float.

In [8]:
# a)
zeros = np.zeros(10)
print("a) zeros:")
print(zeros)

# b)
vowels = np.array(["a", "e", "i", "o", "u"])
print("\nb) vowels:")
print(vowels)

# c)
ones = np.ones((2, 5), dtype=int)
print("\nc) ones:")
print(ones)

# d)
myarray1 = np.array([
    [2.7, -2, -19],
    [0, 3.4, 99.9],
    [10.6, 0, 13]
])
print("\nd) myarray1:")
print(myarray1)

# e)
myarray2 = np.arange(4, 64, 4, dtype=float).reshape((3, 5))
print("\ne) myarray2:")
print(myarray2)

a) zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

b) vowels:
['a' 'e' 'i' 'o' 'u']

c) ones:
[[1 1 1 1 1]
 [1 1 1 1 1]]

d) myarray1:
[[  2.7  -2.  -19. ]
 [  0.    3.4  99.9]
 [ 10.6   0.   13. ]]

e) myarray2:
[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


## 2. Using the arrays created in Exercise 1 above, write NumPy commands for the following:

#### a) Find the dimensions, shape, size, data type of the items and itemsize of arrays _zeros_ , _vowels_ , _ones_ , _myarray1_ and _myarray2_.

#### b) Reshape the array _ones_ to have all the 10 elements in a single row.

#### c) Display the 2nd and 3rd element of the array _vowels_.

#### d) Display all elements in the 2nd and 3rd row of the array _myarray1_.

#### e) Display the elements in the 1st and 2nd column of the array _myarray1_.

#### f) Display the elements in the 1st column of the 2nd and 3rd row of the array _myarray1_.

#### g) Reverse the array of _vowels_

In [9]:
# a)
arrays = {
    "zeros": zeros,
    "vowels": vowels,
    "ones": ones,
    "myarray1": myarray1,
    "myarray2": myarray2
}

for name, arr in arrays.items():
    print(name)
    print("Dimensions:", arr.ndim)
    print("Shape:", arr.shape)
    print("Size:", arr.size)
    print("Data type:", arr.dtype)
    print("Item size:", arr.itemsize, "bytes")
    print()

# b)
print("b) Reshaped ones:")
print(ones.reshape((1, 10)))

# c)
print("\nc) 2nd and 3rd vowels:")
print(vowels[1:3])

# d)
print("\nd) 2nd and 3rd rows of myarray1:")
print(myarray1[1:3, :])

# e)
print("\ne) 1st and 2nd columns of myarray1:")
print(myarray1[:, 0:2])

# f)
print("\nf) 1st column of the 2nd and 3rd rows:")
print(myarray1[1:3, 0])

# g)
print("\ng) vowels in reverse order:")
print(vowels[::-1])

zeros
Dimensions: 1
Shape: (10,)
Size: 10
Data type: float64
Item size: 8 bytes

vowels
Dimensions: 1
Shape: (5,)
Size: 5
Data type: <U1
Item size: 4 bytes

ones
Dimensions: 2
Shape: (2, 5)
Size: 10
Data type: int64
Item size: 8 bytes

myarray1
Dimensions: 2
Shape: (3, 3)
Size: 9
Data type: float64
Item size: 8 bytes

myarray2
Dimensions: 2
Shape: (3, 5)
Size: 15
Data type: float64
Item size: 8 bytes

b) Reshaped ones:
[[1 1 1 1 1 1 1 1 1 1]]

c) 2nd and 3rd vowels:
['e' 'i']

d) 2nd and 3rd rows of myarray1:
[[ 0.   3.4 99.9]
 [10.6  0.  13. ]]

e) 1st and 2nd columns of myarray1:
[[ 2.7 -2. ]
 [ 0.   3.4]
 [10.6  0. ]]

f) 1st column of the 2nd and 3rd rows:
[ 0.  10.6]

g) vowels in reverse order:
['u' 'o' 'i' 'e' 'a']


## 3. Using the arrays created in Exercise 1 from practice, write NumPy commands for the following:

####  a) Divide all elements of array _ones_ by 3.
#### b) Add the arrays _myarray1_ and _myarray2_.
#### c) Subtract _myarray1_ from _myarray2_ and store the result in a new array.
#### d) Multiply _myarray1_ and _myarray2_ elementwise.
#### e) Do the matrix multiplication of _myarray1_ and _myarray2_ and store the result in a new array _myarray3_.
#### f) Divide _myarray1_ by _myarray2_.
#### g) Find the cube of all elements of _myarray1_ and divide the resulting array by 2.
#### h) Find the square root of all elements of _myarray2_ and divide the resulting array by 2. The result should be rounded to two places of decimals.
np.around() OR .round()

In [10]:
# Use this 3x3 array for element-wise operations
myarray2_3x3 = np.arange(4, 40, 4, dtype=float).reshape(3, 3)

# a)
print("a) ones divided by 3:")
print(ones / 3)

# b)
print("\nb) myarray1 + myarray2_3x3:")
print(myarray1 + myarray2_3x3)

# c)
new_arr = myarray2_3x3 - myarray1
print("\nc) myarray2_3x3 - myarray1:")
print(new_arr)

# d)
print("\nd) Element-wise multiplication:")
print(myarray1 * myarray2_3x3)

# e)
myarray3 = myarray1 @ myarray2
print("\ne) Matrix multiplication:")
print(myarray3)

# f)
print("\nf) myarray1 divided by myarray2_3x3:")
print(myarray1 / myarray2_3x3)

# g)
print("\ng) Cube of myarray1 divided by 2:")
print(myarray1 ** 3 / 2)

# h)
print("\nh) Square root of myarray2 divided by 2, rounded to 2 decimals:")
print(np.round(np.sqrt(myarray2) / 2, 2))

a) ones divided by 3:
[[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]]

b) myarray1 + myarray2_3x3:
[[  6.7   6.   -7. ]
 [ 16.   23.4 123.9]
 [ 38.6  32.   49. ]]

c) myarray2_3x3 - myarray1:
[[  1.3  10.   31. ]
 [ 16.   16.6 -75.9]
 [ 17.4  32.   23. ]]

d) Element-wise multiplication:
[[  10.8  -16.  -228. ]
 [   0.    68.  2397.6]
 [ 296.8    0.   468. ]]

e) Matrix multiplication:
[[ -873.2  -946.4 -1019.6 -1092.8 -1166. ]
 [ 4477.2  4890.4  5303.6  5716.8  6130. ]
 [  614.4   708.8   803.2   897.6   992. ]]

f) myarray1 divided by myarray2_3x3:
[[ 0.675      -0.25       -1.58333333]
 [ 0.          0.17        4.1625    ]
 [ 0.37857143  0.          0.36111111]]

g) Cube of myarray1 divided by 2:
[[ 9.841500e+00 -4.000000e+00 -3.429500e+03]
 [ 0.000000e+00  1.965200e+01  4.985015e+05]
 [ 5.955080e+02  0.000000e+00  1.098500e+03]]

h) Square root of myarray2 divided by 2, rounded to 2 decimals:
[[1.   1.41 1.73 2. 

##  4. Create a 2-D array called _myarray4_ using _arange()_ having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result.

####    Using the _myarray4_ created in the above questions, write commands for the following:
##### a) Find the sum of all elements.
##### b) Find the sum of all elements row wise.
##### c) Find the sum of all elements column wise. Notes
##### d) Find the max of all elements.
##### e) Find the min of all elements in each row.
##### f) Find the mean of all elements in each row.
##### g) Find the standard deviation column wise.

In [22]:
myarray4 = np.arange(-1, 9.5, 0.25).reshape(14, 3)
print(myarray4, "\n")

# a)
print("Sum of all elements:")
print(myarray4.sum())

# b)
print("\nSum of each row:")
print(myarray4.sum(axis=1))

# c)
print("\nSum of each column:")
print(myarray4.sum(axis=0))

# d)
print("\nMaximum of all elements:")
print(myarray4.max())

# e)
print("\nMinimum of each row:")
print(myarray4.min(axis=1))

# f)
print("\nMean of each row:")
print(myarray4.mean(axis=1))

# g)
print("\nStandard deviation of each column:")
print(myarray4.std(axis=0))

[[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]] 

Sum of all elements:
173.25

Sum of each row:
[-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]

Sum of each column:
[54.25 57.75 61.25]

Maximum of all elements:
9.25

Minimum of each row:
[-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]

Mean of each row:
[-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]

Standard deviation of each column:
[3.02334666 3.02334666 3.02334666]
